// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v10.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PGNCode) {
  PGNCodeTmfLink = 0,
  PGNCodeTmfId = 1,
};

typedef NS_ENUM(NSUInteger, PGNTMAVersion) {
  PGNTMAVersionDevelop = 0,
  PGNTMAVersionPreview = 1,
  PGNTMAVersionAudit = 2,
  PGNTMAVersionOnline = 3,
  PGNTMAVersionLocal = 4,
};

@class PGNMessageData;

@interface PGNMessageData : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(PGNCode)code
    data:(NSDictionary<NSString *, NSString *> *)data;
@property(nonatomic, assign) PGNCode code;
@property(nonatomic, strong) NSDictionary<NSString *, NSString *> * data;
@end

/// The codec used by PGNTmfFlutterApi.
NSObject<FlutterMessageCodec> *PGNTmfFlutterApiGetCodec(void);

/// Native call Flutter
@interface PGNTmfFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)logoutWithCompletion:(void (^)(FlutterError *_Nullable))completion;
@end

/// The codec used by PGNTmfHostApi.
NSObject<FlutterMessageCodec> *PGNTmfHostApiGetCodec(void);

@protocol PGNTmfHostApi
- (void)initTmfWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)loginTmfAccount:(NSString *)account password:(NSString *)password isOpenLogin:(NSNumber *)isOpenLogin completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)destroyWithCompletion:(void (^)(FlutterError *_Nullable))completion;
- (void)sendMessageMessage:(PGNMessageData *)message completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void PGNTmfHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNTmfHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
